.TH TIMESTAMP 1
.SH NAME
timestamp \-   prefix each line with a timestamp
.SH SYNOPSIS
<some command(s)> |
.B timestamp [FORMAT]
.SH DESCRIPTION
timestamp prefixes each line received on standard input with a
timestamp in the format YYYY-MM-DD HH:MM:SS.
.SH EXAMPLE
  $ (echo A; sleep 2s; echo B; sleep 3s; echo C) | timestamp
  2011-03-14 20:58:58     A
  2011-03-14 20:59:00     B
  2011-03-14 20:59:03     C
  $ 
.SH DEVELOPMENT
The source code can be found in this git repository: http://koldfront.dk/git/timestamp/
.SH AUTHOR
Klaus Alexander Seistrup <klaus@seistrup.dk>
.SH COPYRIGHT
Copyright (C) 2011, Klaus Alexander Seistrup. License GPLv2+: GNU GPL version 2+.
.SH SEE ALSO
strftime(3) for date and time conversion specifications.
ts(1) from the moreutils package.
